#!/usr/bin/env node
/**
 * Build the Cloudflare Worker (worker.js) from sources in src/.
 * Embeds each asset as a JSON-stringified string — bulletproof escaping, no
 * backtick / ${} / </script> hazards.
 *
 * Run after editing src/*:    node build.mjs
 * Then deploy:                 wrangler deploy
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const VERSION = '1.3.0';

const tracker = readFileSync(join(here, 'src/funnel-tracker.js'), 'utf8');
const guide = readFileSync(join(here, 'src/guide.html'), 'utf8');
const llms = readFileSync(join(here, 'src/llms.txt'), 'utf8');

const J = (s) => JSON.stringify(s);

const worker = `// worker.js — Cloudflare Worker for cdn.founderplus.id
// GENERATED by build.mjs — do not edit by hand. Edit src/* then re-run.
var VERSION = ${J(VERSION)};
var TRACKER_SCRIPT = ${J(tracker)};
var GUIDE_HTML = ${J(guide)};
var LLMS_TXT = ${J(llms)};

var CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type"
};
var JS_HEADERS = {
  ...CORS,
  "Content-Type": "application/javascript; charset=utf-8",
  "Cache-Control": "public, max-age=3600, s-maxage=86400",
  "CDN-Cache-Control": "max-age=86400",
  "X-Content-Type-Options": "nosniff"
};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const p = url.pathname;
    if (request.method === "OPTIONS") return new Response(null, { headers: CORS });

    if (p === "/funnel-tracker.js") {
      return new Response(TRACKER_SCRIPT, { headers: JS_HEADERS });
    }
    if (p === "/funnel-tracker.min.js") {
      const min = TRACKER_SCRIPT.replace(/\\/\\*[\\s\\S]*?\\*\\//g, "").replace(/\\s+/g, " ");
      return new Response(min, { headers: JS_HEADERS });
    }
    if (p === "/" || p === "/guide" || p === "/guide.html") {
      return new Response(GUIDE_HTML, {
        headers: { ...CORS, "Content-Type": "text/html; charset=utf-8", "Cache-Control": "public, max-age=3600, s-maxage=86400" }
      });
    }
    if (p === "/llms.txt") {
      return new Response(LLMS_TXT, {
        headers: { ...CORS, "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=3600, s-maxage=86400" }
      });
    }
    if (p === "/health") {
      return new Response(JSON.stringify({ status: "ok", version: VERSION, timestamp: Date.now() }), {
        headers: { ...CORS, "Content-Type": "application/json" }
      });
    }
    return new Response("Not Found", { status: 404, headers: CORS });
  }
};
`;

writeFileSync(join(here, 'worker.js'), worker);
console.log(`worker.js: ${worker.length} bytes (tracker ${tracker.length} + guide ${guide.length} + llms ${llms.length})`);
